### ISSUE TITLE
Feature support - parameterized scopes

### ISSUE THREAD

**Issue by catmando** [geneeblack/graphql_model_mapper#19]
This would be important to our project.  Would it be very hard to add? If not perhaps I will do a PR.

FYI the project is http://ruby-hyperloop.org  See issue [hyper-model/issues/9](https://github.com/ruby-hyperloop/hyper-model/issues/9)

**Comment by geneeblack** [comment]
@catmando I think the problem with parameterized scopes might be the discovery of the parameters and default type casting of those parameters needed to exercise the scope. Although if the definition of the scopes were provided to the generator from the model then you wouldn't need to discover them, you would just need to have some way to validate them.

Alternatively, you could build your own argument list for the inputs for a query (or delete mutation) including your customized inputs arguments for parameterized scopes (not sure the argument list is currently setup correctly for the override on the master branch but it's only a couple lines of code to get it to work) and then override the resolve on the model with your own resolve to include use of your parameterized scope arguments. 

Alternatively, I'm a few days away from providing a global resolve wrapper capability (along with some other nuggets on the relayimprovements branch including firming up the argument override) that may be useful for this purpose. 

If you want to give it a whirl feel free to submit a PR. It may be an option on the default arguments for queries and delete mutations that could be used by others.

**Comment by geneeblack** [comment]
@catmando Took a look at hyperloop, some pretty cool stuff. Will have to carve out some time to take it on a test drive since my next direction was to research react with graphql. Looks like ya'll have already implemented to the nth degree some of the things I was interested in discovering.

**Comment by geneeblack** [comment]
@catmando I've done a little exploratory work with implementing scopes with parameters and here is what I've found.

1. I've been unable to find a proper arity for scope methods because of the way that they are wrapped in rails. 

https://github.com/rails/rails/blob/4cc1c14493e7a9bd188ee13c237366f6bc2e13f4/activerecord/lib/active_record/scoping/named.rb#L158

They all end up having a -1 arity to accept any number of parameters, even if defined as a lambda that should only accept a specific number of parameters. Even though the arity is -1 they then fail if not given the proper number of parameters. If you know of a way to retrieve the proper number of parameters from a scope method that would be helpful.

2. Since I'm unable to even determine the number of params at this point it's still a little loose, too loose for what I'd like to accomplish. I suppose I could tighten it up to the point where it would depend on the definition being sent, but without a way to verify the user definition it would still be loose.

I'm not giving up, just trying to find a way to tighten it a bit. It would be easier if the scope were defined as a class method instead of being wrapped in the scope declaration. Class methods have a specific arity, so then I would at least be able to verify the number of parameters defined.


https://github.com/geneeblack/graphql_model_mapper/tree/parameterized_scopes

In that branch I am accepting an input argument of scopes (if scopes are defined in the graphql_query macro method). The argument accepts an array of {scope: scope_enum, arguments: string.array} to specify the scopes with their params to be chained when the query is run. As I said, since there is no way to know the limit of the number of parameters for a given scope, it can err if not given the proper number of parameters in the parameters string array.

**Comment by geneeblack** [comment]
In that branch, given a scope method on a model:

    scope :find_lazy, -> (id) { where(id: id) }

and a graphql_query macro definition

    graphql_query scope_methods: [:find_lazy]
you would be able to send a qraphql query to that model such as:

    query{ model(scopes: [{scope: find_lazy, arguments: ["8"]}])
     {
        items {
          edges {
            node {
              item_id
            }
          }
        }
      }
    }

if you attempted to send the wrong number of parameters to the query 

    query{ model(scopes: [{scope: find_lazy, arguments: ["8", "9"]}])

you would receive a GraphQL:ExecutionError in the form:

    {
      "data": {
        "model": null
      },
      "errors": [
        {
          "message": "scope method: Model.find_lazy arguments: [\"8\", \"9\"] error: wrong number of arguments (2 for 1)",
          "locations": [
            {
              "line": 2,
              "column": 3
            }
          ],
          "path": [
            "model"
          ]
        }
      ]
    }

since I'm not able to determine the number and types of arguments for the scope, right now the parameters are limited to string types that need to be coercible in the scope method. In this simple case, they are.

**Comment by geneeblack** [comment]
I've merged this capability into the master branch #26

**Comment by catmando** [comment]
@geneeblack Well you beat me to it... but I have been thinking hard with some other of the hyperloop core team, and one question has come up: how do you chain scopes?

I.e. `some_user.todos.active.due_after('5/1/2018')` etc.

**Comment by geneeblack** [comment]
since the query is not materialized until it is converted into an array until later in the process it is as simple as applying the scope methods iteratively on the query object.

The scopes are entered as an array to the query in the form scopes:[{scope:, arguments:},{:scope, :arguments}...]  and in the resolve that array is iterated and each scope is validated (to ensure the method is valid, even though it is constrained by the ScopeEnum), then applied using the send method with *arguments.

https://github.com/geneeblack/graphql_model_mapper/blob/master/lib/graphql_model_mapper/resolve.rb#L28

The query is tested for correctness applying a limit(0) before it is sent down the resolve chain

https://github.com/geneeblack/graphql_model_mapper/blob/master/lib/graphql_model_mapper/resolve.rb#L125

where it is later materialized in its entirety by GraphQL

**Comment by catmando** [comment]
We had kind of different thought, that I wanted to run by you (let me know if there is a better way to discuss than adding stuff here...)

For each Model class the following Type would be generated:

```graphql
type MyModelCollection {
  all: [MyModelCollection]
  scope(method: String, params: [String] = []): MyModelCollection
  count: Int
  # any other standard scope instance methods
  }
```
now i can say:
```graphql
type MyOtherModel ... {
  my_models: MyModelCollection # i.e. in AR this was has_many :my_models
  ...
}
```

and in the graph

```graphql
  my_other_model(id: 123) { 
    my_models { scope('some_scope', 1, 2, 'blah') { scope('another_scope') { all } } ... }
  }
```

**Comment by geneeblack** [comment]
So instead of passing in your scope in the input arguments you are adding them as output selection elements (with arguments)? Would each of these scope elements then return a separate set of records? Or are you placing them in the selection to be used as filters for the  all output?

I think maybe what you are wanting is access to scopes in nested has_many relationships. i.e. to be able to filter the nested relationship based on the scope value available with the nested model. Would adding the input arguments to the has_many relationships/types get you there as well? Similar to the paging elements already available? (first,last,after,before)

I'd have to see how that would affect the resolve flow and the impact it would have, although right now the optional limits being set on the nested records is already having a similar effect on the nested relationship selection. I would be hesitant to add them as sibling elements since that would allow two different sets of records to be retrieved, one for the all element and one for scoped element. Unless that is not what you are intending. (your third example shows all being nested under scope, whereas your first example shows them as sibling elements?).

**Comment by catmando** [comment]
I think the above example would return something like this:
```graphql
my_other_model { my_models { scope { scope {all: [.... the actual collection ...] } }  }
```
I've not tried this, its just a paper experiment, but it would seem to allow direct translation of some AR expression like `MyOtherModel.find(123).my_models.some_scope.another_scope` to a query.

**Comment by catmando** [comment]
This is roughly how we do it in hyperloop... although we are not using graphql (yet) the idea is the same.  Client passes a request tree to the server, and then server walks down the tree, generating the response.  

WIthout more graphQL experience I don't know if what I am suggesting is practical.  It would require that the scope's resolver be able to return or save in some context the intermediate AR expressions, like we do in hyperloops tree walker.

**Comment by geneeblack** [comment]
The resolve tree does indeed pass an object context (query) which could be modified by applying scope, limit... further down the chain, essentially treating it as a separate query that already has its references set to the parent record. Currently it imposes a limit in this way for the child records. I don't think it would be too much effort to include the same selection criteria that is currently available in the parent root type  on the child collections (has_many references). Originally I hesitated to do that because of the n+1 query implications. But with paging information already being set I've already crossed that bridge and am doing n+1 queries to filter the child records by those limits. 

Let me see if I can put something together, assuming that nested record filtering is the feature you are wanting.

**Comment by catmando** [comment]
hmmm... but if you can somehow just pass each AR scope result down as the context then there should not be n+1 queries.  In my simple example there would only be two AR queries executed:  find(123) and then `my_models.some_scope.another_scope.all`

**Comment by geneeblack** [comment]
Imposing the child limits forces a separate query to be made (unless those limits are imposed on the original collected array rather than being sent back to the server). 

Imposing it on the original returned array has its own set of issues depending on the size of that array (which of course can't be determined until that array query is already materialized).  GraphQL does indeed use the resultant array to set its (first,last,before,after) inputs as well as it's pageInfo information. I opted to let the server do that work in my :flat representation (even though it doesn't do everything that GraphQL's Relay structure performs). GraphQL's relay structure pretty much requires it to work on the returned array since it needs to set some internal values to be filtered upon (cursor).

That being said, applying a scope would require revisiting the server since I don't think I'd be able to apply the scope to a previously returned array.

In your example (with one nesting) the scope would be applied to each subsequent child nesting for each parent. i.e. the reference passed to each child nesting is its relationship to the parent, child_parent_id = parent_id. Each scope would be a result of applying the scope to that reference..  child_parent_id = parent_id AND scope, so for each parent record there would be an n+1 query performed for its child relationships. Unless you think applying the scope can be done in a different way.

Otherwise, if you had those scopes set on different has_many references and they were already preset on the collections

    has_many :all_items 
    has_many :scoped_items -> {where some condition}

then it would not take the additional query hit since those records would be materialized on the original query in the left join of those items

**Comment by catmando** [comment]
I guess what I am not being clear on mainly because I don't even know what is possible...

but if you look at those type definitions, the *only* field that is an array is `all` field. 

Maybe this doesn't work the way I think it does in GraphQL?

**Comment by geneeblack** [comment]
Let me look into it more to determine exactly what the implications are, I may be being too skeptical at this point and only thinking about my :flat representation using lists. I'll have to see how GraphQL will treat it in it's GraphQL::Relay::ConnectionType class.

Assuming the base need is to impose filtering on child collections with the primary concern being able to apply scope to those child relations.

**Comment by catmando** [comment]
yeah, I think your current structure of passing the chain of scopes as a param to the outer field call is fine... I was just curious if you think what we came up would work.

**Comment by geneeblack** [comment]
well, I did get it working the way I was thinking about it, but it does cause n+1 queries if selection criteria are added at the nested level. Let me stew on it a bit to see if I can approach it in a different way.

**Comment by geneeblack** [comment]
what I have right now is in the parameterized_scopes_2 branch, it's a bit messy but essentially it is applying the same selection availability on the nested has_many relationship as is available on the root item, i.e.


    {
      post(item_ids: [37, 322]) {
        items {
          edges {
            node {
              item_id
              comments(scopes: {scope: has_content}) {
                items {
                  edges {
                    node {
                      item_id
                      content
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

The issue, I believe, is that I need to use the information for the nested select on the original resolve. It is available in the document tree, just a bugger to retrieve it at that point. Adding the selection criteria at a later point (when it reaches the comments reference) is causing the additional queries to be initiated since it has already resolved the top level.

Like I said, let me think on it a bit. I don't think it's impossible.

**Comment by geneeblack** [comment]
The queries that emerge from that are:

      Post Load (0.6ms)  SELECT `posts`.* FROM `posts` WHERE (`posts`.id in (37,322)) LIMIT 100
      Comment Load (0.5ms)  SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` IN (37, 322)
      Comment Load (0.6ms)  SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = 37 AND (comments.content > '') LIMIT 100
      Comment Load (0.6ms)  SELECT `comments`.* FROM `comments` WHERE `comments`.`post_id` = 322 AND (comments.content > '') LIMIT 100
      Completed 200 OK in 29.3ms (Views: 1.0ms | ActiveRecord: 2.7ms)

The scope has_content on comment.rb model is

    scope :has_content, -> () { where("comments.content > ''") }


I need to trace back to where the original comments selection is being done correctly (as part of the included tables on the original query) and be able to apply the scope there rather than waiting until later to apply the scope.
